### ISSUE TITLE
Typo line 670 @index.js

### ISSUE THREAD

**Issue by nivranaitsirhc** [ericz1803/react-google-calendar#11]
Hi! I would like to say thank you for this module. It helps a lot.

Using v3 found a typo forgot to add '_' at new `newEvent` variable causing a undefined error

**Comment by ericz1803** [comment]
Hi, this typo should be fixed now. Could you do me a favor and check the console and see if there is anything being printed as "Not categorized" because that means that there is another type of event that the calendar is not displaying.

**Comment by nivranaitsirhc** [comment]
Actually when I manually fixed this on my copy. It does show two instances of `not supported` in my browsers console.
