### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by Rendydendimara** [ericz1803/react-google-calendar#18]
Is this ilbrary type support for Typescript? How do I do the setup.

**Comment by ericz1803** [comment]
Hi! Currently it doesn't support typescript. I am not very familiar with typescript, but I will look into supporting it. If you are more familiar with it/want to do it yourself, you are welcome to make a pull request for it.

**Comment by artygrand** [comment]
Hello, @ericz1803 I added this typing to myself and it's works

react-google-calendar.d.ts
```
declare module '@ericz1803/react-google-calendar' {
    import * as React from 'react';

    declare class Calendar extends React.Component<CalendarProps> {}

    export interface CalendarProps {
        calendars: {
            calendarId: string,
            color?: string,
        }[],
        apiKey: string,
        showFooter?: boolean,
        showArrow?: boolean,
        styles?: object,
        language?: string
    }

    export default Calendar;
}
```

BTW, `showFooter` in your `Calendar.propTypes` isn't really required
