### ISSUE TITLE
New Language

### ISSUE THREAD

**Issue by DiegoRodriguez93** [ericz1803/react-google-calendar#19]
Hi Eric! 

I love your calendar, can I send a PR with Spanish and a new prop to handle the language?

**Comment by ericz1803** [comment]
Thanks! Go ahead and open up a pull request and I'll take a look.

**Comment by DiegoRodriguez93** [comment]
Please take a look when you have a while!

**Comment by ericz1803** [comment]
Hi Diego!

Thanks for the pull request. Your changes are published in v4.2.0.

-Eric
