### ISSUE TITLE
Support for Next.js

### ISSUE THREAD

**Issue by FunctionDJ** [ericz1803/react-google-calendar#23]
It would be awesome if this component could support Next.js.
It doesn't work right now because this module is importing CSS from `node_modules`, which Next.js ["cannot support"](https://nextjs.org/docs/messages/css-npm).

I've been looking for a Google Calendar component for Next.js for quite a while now, and this one looks really nice. Too bad i can't use it =(

**Comment by konichar** [comment]
I just ran into this problem right now, I hope we can get a fix soon, nextjs is rejecting this library

**Comment by italomarcos1** [comment]
Good news.

https://github.com/vercel/next.js/discussions/27953
