### ISSUE TITLE
Does not work with react 17

### ISSUE THREAD

**Issue by matthewwen** [ericz1803/react-google-calendar#30]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: purdue-ecea-website@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.8.0" from @emotion/react@11.4.1
npm ERR!   node_modules/@emotion/react
npm ERR!     @emotion/react@"^11.4.1" from the root project
npm ERR!     peer @emotion/react@"^11.1.1" from @ericz1803/react-google-calendar@4.2.1
npm ERR!     node_modules/@ericz1803/react-google-calendar
npm ERR!       @ericz1803/react-google-calendar@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.14.0" from @ericz1803/react-google-calendar@4.2.1
npm ERR! node_modules/@ericz1803/react-google-calendar
npm ERR!   @ericz1803/react-google-calendar@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by shahdivyank** [comment]
One way to resolve this is by using yarn instead: 

yarn add @ericz1803/react-google-calendar

It worked out for me.
