### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by lucaamrein** [ericz1803/react-google-calendar#31]
The library does not work with next.js, because styles are incorrectly imported.
See: https://nextjs.org/docs/messages/css-npm
![image](https://user-images.githubusercontent.com/62956729/132573161-96644ca1-54cc-4ba8-b887-c4e5e78f11f5.png)

**Comment by codemonkey800** [comment]
This can be fixed by either bundling the CSS into the JS, or if we make users import the CSS directly.

**Comment by Salemoche** [comment]
> 

how would i do that?

**Comment by Salemoche** [comment]
> This can be fixed by either bundling the CSS into the JS, or if we make users import the CSS directly.

@codemonkey800  How would I do that?

**Comment by ytakayanagi** [comment]
I'll leave this comment if anyone is struggling with the error. I've tested my method in Next.js version 11 and it works.

1. Install "next-transpile-modules" and "@babel/preset-react"
```
# yarn
yarn add next-transpile-modules @babel/preset-react

# npm
npm i next-transpile-modules @babel/preset-react
```
2. Create or modify your next.config.js
```
const withTM = require("next-transpile-modules")([
  "@ericz1803/react-google-calendar"
])

module.exports = withTM({
  // existing custom config
});
```
3. Import CSS in "_app.js" or "_app.tsx" file
```
import'@ericz1803/react-google-calendar/index.css'
```

**Comment by garv-shah** [comment]
@ytakayanagi Thank you so much for the fix! For me it seemed to be a step forward, since the page actually started rendering, but the formatting is very broken, and looks like this:

![SCR-20230226-mmw](https://user-images.githubusercontent.com/64292655/221393758-cdb78afb-e4a7-414f-90c2-8a2232d13c3d.png)

Any idea what could be causing this?

**Comment by ytakayanagi** [comment]
@garv-shah Glad, you got it to work! From the looks, the style is the only thing that needs to be fixed for you. Did you add:
`import'@ericz1803/react-google-calendar/index.css'`
You can add this import directly to the component that is displaying the calendar.

**Comment by garv-shah** [comment]
Yup, the import statement is there, but it doesn't seem to make a difference, in fact it looks the same if I have it there or remove it :/

**Comment by breezyfasano** [comment]
I am having the same issue with NextJS!
