### ISSUE TITLE
Duplicate event

### ISSUE THREAD

**Issue by Danneytrieu** [ericz1803/react-google-calendar#50]
I'm having a duplication on my tested event in my React webpage, does anyone else experiencing this ?

![Screen Shot 2022-10-04 at 10 35 33 AM](https://user-images.githubusercontent.com/89677528/193875516-1032f7b7-ae40-4857-88df-18ad6c27619e.png)

**Comment by Danneytrieu** [comment]
<img width="651" alt="Screen Shot 2022-10-04 at 10 37 48 AM" src="https://user-images.githubusercontent.com/89677528/193876696-dda6d10b-6aa0-41d2-9e52-64bd327dbdaf.png">

**Comment by IdleScV** [comment]
yup I'm getting this same thing

**Comment by carlos-molero** [comment]
same here

**Comment by sejun99** [comment]
same here

**Comment by vaedgra** [comment]
> So, mine worked copying the code from index.js. I don't know this will fix anybody who has this problems, but maybe work on index.js?

It's not working with React18, because:
> **Deprecations**
> `react-dom`: `ReactDOM.render` has been deprecated. Using it will warn and run your app in React 17 mode.

**Comment by vaedgra** [comment]
This module is only working with React16 and could work with 17 (I haven't checked that).
I do use React18 and tried to implement this module, but had the same issue with duplicates.

The already given solution from @sejun99 with the modification of index.js is at least not working for React18, because:
> **Deprecations**
> `react-dom`: `ReactDOM.render` has been deprecated. Using it will warn and run your app in React 17 mode.

**Comment by 0xadada** [comment]
I have this problem in Next.js too, but when I run a  production build it stops showing doubles 🤷
