### ISSUE TITLE
Can not resolve @emotion/css

### ISSUE THREAD

**Issue by JoaoCEAlmeida** [ericz1803/react-google-calendar#8]
Hi,
I'm getting the following error after instaling the package:

![image](https://user-images.githubusercontent.com/9196047/99712394-e4fc4400-2a9a-11eb-9e6b-3480a2b26b15.png)

Thanks in advance.

**Comment by ericz1803** [comment]
Hi, it looks like emotion updated to v11 so for now, run `@emotion/core@10.0.28` to use emotion v10. I updated the readme to reflect these changes and it worked when I tested it. Let me know if you have any more issues or questions.

**Comment by JoaoCEAlmeida** [comment]
Worked @ericz1803. Thank you!
